language: node_js
env: CI=true
sudo: false


#branches:
#  only:
#    - master

node_js:
  - "latest"
  - "0.12"
  - "0.10"
after_script:
  - npm run coveralls
notifications:
  email:
    - qiuzhongleiabc@126.com

